language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
install:
  - pip install -e .[tests]
script:
  - make test
# https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email:
    on_success: never
    on_failure: always
